CREATE TABLE "accounts" (
	"id"	INTEGER,
	"first_name"	TEXT NOT NULL,
	"last_name"	TEXT NOT NULL,
	"email"	TEXT NOT NULL UNIQUE,
	"password"	TEXT NOT NULL,
	"date_created"	DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("id" AUTOINCREMENT)
);

CREATE TABLE "donations" (
	"id"	INTEGER,
	"user_id"	INTEGER NOT NULL,
	"country" TEXT NOT NULL,
	"value" INTEGER NOT NULL,
	"date_created"	DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("id" AUTOINCREMENT),
	FOREIGN KEY(user_id) REFERENCES accounts(id)
);